package main

import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

func main() {
	fmt.Println(fibonacci())
}

func fibonacci() int {
	current, next, sum := 1, 2, 2
	for {
		previous := current
		current = next
		next = previous + current
		if next >= 4000000 {
			break
		}
		if next%2 == 0 {
			sum += next
		}
	}
	return sum
}
